let id = localStorage.getItem("id");
let playerId = localStorage.getItem("playerId");
const teamsData = [
  {
    id: 0,
    name: "CSK",
    logo: "./Assets/Teams/Chennai.jpg",
    "chamiponship count": 4,
    captain: "Mahendra Singh Dhoni",
    "top batsman": "Suresh Raina",
    "top bowler": "Ravichandran Ashwin",
    color: "linear-gradient(160deg,rgb(5, 156, 194),rgb(250, 174, 9))",
    players: [
      {
        id: 0,
        playerName: "MSDhoni",
        player_Name: "M S Dhoni",
        team_Name: "CSK",
        price: "$5.1 Cr (INR)",
        isPlaying: true,
        status: "Playing",
        description: "Batsman",
      },
      {
        id: 1,
        playerName: "RavindraJadeja",
        player_Name: "Ravindra Jadeja",
        team_Name: "CSK",
        price: "$11.0 Cr (INR)",
        isPlaying: true,
        status: "Playing",
        description: "All-rounder",
      },
      {
        id: 2,
        playerName: "MoeenAli",
        player_Name: "Moeen Ali",
        team_Name: "CSK",
        price: "$8.0 Cr (INR)",
        isPlaying: true,
        status: "Playing",
        description: "All-rounder",
      },
      {
        id: 3,
        playerName: "RajvardhanHangargekar",
        player_Name: "Rajvardhan Hangargekar",
        team_Name: "CSK",
        price: "$5.3 Cr (INR)",
        isPlaying: true,
        status: "Playing",
        description: "Bowler",
      },
      {
        id: 4,
        playerName: "RuturajGaikwad",
        player_Name: "Ruturaj Gaikwad",
        team_Name: "CSK",
        price: "$7.0 Cr (INR)",
        isPlaying: true,
        status: "Playing",
        description: "Batsman",
      },
      {
        id: 5,
        playerName: "AmbatiRayudu",
        player_Name: "Ambati Rayudu",
        team_Name: "CSK",
        price: "$13.0 Cr (INR)",
        isPlaying: true,
        status: "Playing",
        description: "Batsman",
      },
      {
        id: 6,
        playerName: "DwainePretorius",
        player_Name: "Dwaine Pretorius",
        team_Name: "CSK",
        price: "$4.5 Cr (INR)",
        isPlaying: true,
        status: "Playing",
        description: "All-rounder",
      },
      {
        id: 7,
        playerName: "BhagathVarma",
        player_Name: "Bhagath Varma",
        team_Name: "CSK",
        price: "$5.0 Cr (INR)",
        isPlaying: true,
        status: "Playing",
        description: "All-rounder",
      },
      {
        id: 8,
        playerName: "SimarjeetSingh",
        player_Name: "Simarjeet Singh",
        team_Name: "CSK",
        price: "$2.4 Cr (INR)",
        isPlaying: true,
        status: "Playing",
        description: "Bowler",
      },
      {
        id: 9,
        playerName: "PrashantSolanki",
        player_Name: "Prashant Solanki",
        team_Name: "CSK",
        price: "$5.1 Cr (INR)",
        isPlaying: true,
        status: "Playing",
        description: "Bowler",
      },
      {
        id: 10,
        playerName: "ChrisJordan",
        player_Name: "Chris Jordan",
        team_Name: "CSK",
        price: "$1.3 Cr (INR)",
        isPlaying: true,
        status: "Playing",
        description: "Bowler",
      },
      {
        id: 11,
        playerName: "AdamMilne",
        player_Name: "Adam Milne",
        team_Name: "CSK",
        price: "$30 Lakhs (INR)",
        isPlaying: false,
        status: "On-bench",
        description: "Bowler",
      },
    ],
  },
  {
    id: 1,
    name: "DC",
    logo: "./Assets/Teams/Delhi.jpg",
    "chamiponship count": 0,
    captain: "Shreyas Iyer",
    "top batsman": "Shreyas Iyer",
    "top bowler": "Kagiso Rabada",
    color: "linear-gradient(160deg,rgb(12, 117, 236),rgb(253, 69, 23))",
    players: [
      {
        id: 0,
        playerName: "DavidWarner",
        player_Name: "David Warner",
        team_Name: "DC",
        price: "$23 Cr (INR)",
        isPlaying: true,
        status: "Playing",
        description: "Batsman",
      },
      {
        id: 1,
        playerName: "PrithviShaw",
        player_Name: "Prithvi Shaw",
        team_Name: "DC",
        price: "$10.0 Cr (INR)",
        isPlaying: true,
        status: "Playing",
        description: "All-rounder",
      },
      {
        id: 2,
        playerName: "MitchellMarsh",
        player_Name: "Mitchell Marsh",
        team_Name: "DC",
        price: "$7.8 Cr (INR)",
        isPlaying: true,
        status: "Playing",
        description: "All-rounder",
      },
      {
        id: 3,
        playerName: "RishabhPant",
        player_Name: "Rishabh Pant",
        team_Name: "DC",
        price: "$13.0 Cr (INR)",
        isPlaying: true,
        status: "Playing",
        description: "Batsman",
      },
      {
        id: 4,
        playerName: "SarfarazKhan",
        player_Name: "Sarfaraz Khan",
        team_Name: "DC",
        price: "$5.8 Cr (INR)",
        isPlaying: true,
        status: "Playing",
        description: "Batsman",
      },
      {
        id: 5,
        playerName: "KuldeepYadav",
        player_Name: "Kuldeep Yadav",
        team_Name: "DC",
        price: "$5.3 Cr (INR)",
        isPlaying: true,
        status: "Playing",
        description: "Bowler",
      },
      {
        id: 6,
        playerName: "AxarPatel",
        player_Name: "Axar Patel",
        team_Name: "DC",
        price: "$4.7 Cr (INR)",
        isPlaying: true,
        status: "Playing",
        description: "All-rounder",
      },
      {
        id: 7,
        playerName: "LungisaniNgidi",
        player_Name: "Lungisani Ngidi",
        team_Name: "DC",
        price: "$7.9 Cr (INR)",
        isPlaying: true,
        status: "Playing",
        description: "All-rounder",
      },
      {
        id: 8,
        playerName: "UmeshYadav",
        player_Name: "Umesh Yadav",
        team_Name: "DC",
        price: "$28 Lakhs (INR)",
        isPlaying: true,
        status: "Playing",
        description: "Bowler",
      },
      {
        id: 9,
        playerName: "LalitYadav",
        player_Name: "Lalit Yadav",
        team_Name: "DC",
        price: "$96 Lakhs (INR)",
        isPlaying: true,
        status: "Playing",
        description: "Bowler",
      },
      {
        id: 10,
        playerName: "TimSeifert",
        player_Name: "Tim Seifert",
        team_Name: "DC",
        price: "$1.3 Cr (INR)",
        isPlaying: true,
        status: "Playing",
        description: "Bowler",
      },
      {
        id: 11,
        playerName: "YashDhull",
        player_Name: "Yash Dhull",
        team_Name: "DC",
        price: "$30 Lakhs (INR)",
        isPlaying: true,
        status: "On-bench",
        description: "Bowler",
      },
    ],
  },
  {
    id: 2,
    name: "KKR",
    logo: "./Assets/Teams/Kolkata.jpg",
    "chamiponship count": 2,
    captain: "Eoin Morgan",
    "top batsman": "Shubman Gill",
    "top bowler": "Varun Chakravarthy",
    color: "linear-gradient(160deg,rgb(3, 2, 97),rgb(201, 156, 10))",
    players: [
      {
        id: 0,
        playerName: "VenkateshIyer",
        player_Name: "Venkatesh Iyer",
        team_Name: "KKR",
        price: "$4.0 Cr (INR)",
        isPlaying: true,
        status: "Playing",
        description: "Batsman",
      },
      {
        id: 1,
        playerName: "NitishRana",
        player_Name: "Nitish Rana",
        team_Name: "KKR",
        price: "$10.0 Cr (INR)",
        isPlaying: true,
        status: "Playing",
        description: "All-rounder",
      },
      {
        id: 2,
        playerName: "AndreRussell",
        player_Name: "Andre Russell",
        team_Name: "KKR",
        price: "$8.5 Cr (INR)",
        isPlaying: true,
        status: "Playing",
        description: "All-rounder",
      },
      {
        id: 3,
        playerName: "ShreyasIyer",
        player_Name: "Shreyas Iyer",
        team_Name: "KKR",
        price: "$13.3 Cr (INR)",
        isPlaying: true,
        status: "Playing",
        description: "Batsman",
      },
      {
        id: 4,
        playerName: "SunilNarine",
        player_Name: "Sunil Narine",
        team_Name: "KKR",
        price: "$5.0 Cr (INR)",
        isPlaying: true,
        status: "Playing",
        description: "Batsman",
      },
      {
        id: 5,
        playerName: "TimSouthee",
        player_Name: "Tim Southee",
        team_Name: "KKR",
        price: "$5.3 Cr (INR)",
        isPlaying: true,
        status: "Playing",
        description: "Bowler",
      },
      {
        id: 6,
        playerName: "AshokSharma",
        player_Name: "Ashok Sharma",
        team_Name: "KKR",
        price: "$4.9 Cr (INR)",
        isPlaying: true,
        status: "Playing",
        description: "All-rounder",
      },
      {
        id: 7,
        playerName: "MohammadNabi",
        player_Name: "Mohammad Nabi",
        team_Name: "KKR",
        price: "$7.0 Cr (INR)",
        isPlaying: true,
        status: "Playing",
        description: "All-rounder",
      },
      {
        id: 8,
        playerName: "UmeshYadav",
        player_Name: "Umesh Yadav",
        team_Name: "KKR",
        price: "$23 Lakhs (INR)",
        isPlaying: true,
        status: "Playing",
        description: "Bowler",
      },
      {
        id: 9,
        playerName: "RasikhSalam",
        player_Name: "Rasikh Salam",
        team_Name: "KKR",
        price: "$67 Lakhs (INR)",
        isPlaying: true,
        status: "Playing",
        description: "Bowler",
      },
      {
        id: 10,
        playerName: "PrathamSingh",
        player_Name: "Pratham Singh",
        team_Name: "KKR",
        price: "$1.3 Cr (INR)",
        isPlaying: true,
        status: "Playing",
        description: "Bowler",
      },
      {
        id: 11,
        playerName: "AlexHales",
        player_Name: "Alex Hales",
        team_Name: "KKR",
        price: "$38 Lakhs (INR)",
        isPlaying: true,
        status: "On-bench",
        description: "Bowler",
      },
    ],
  },
  {
    id: 3,
    name: "MI",
    logo: "./Assets/Teams/Mumbai.jpg",
    "chamiponship count": 5,
    captain: "Rohit Sharma",
    "top batsman": "Ishan Kishan",
    "top bowler": "Jasprit Bumrah",
    color:
      "linear-gradient(160deg,rgb(255, 123, 0),rgb(255, 230, 0),rgb(158, 197, 18),rgb(13, 95, 13))",
    players: [
      {
        id: 0,
        playerName: "RohitSharma",
        player_Name: "Rohit Sharma",
        team_Name: "MI",
        price: "$5.1 Cr (INR)",
        isPlaying: true,
        status: "Playing",
        description: "Batsman",
      },
      {
        id: 1,
        playerName: "ik",
        player_Name: "Ishan Kisan",
        team_Name: "MI",
        price: "$15.8 Cr (INR)",
        isPlaying: true,
        status: "Playing",
        description: "Batsman",
      },
      {
        id: 2,
        playerName: "SuryakumarYadav",
        player_Name: "Suryakumar Yadav",
        team_Name: "MI",
        price: "$5.9 Cr (INR)",
        isPlaying: true,
        status: "Playing",
        description: "Batsman",
      },
      {
        id: 3,
        playerName: "KieronPollard",
        player_Name: "Kieron Pollard",
        team_Name: "MI",
        price: "$9.0Cr (INR)",
        isPlaying: true,
        status: "Playing",
        description: "All-rounder",
      },
      {
        id: 4,
        playerName: "JaspritBumrah",
        player_Name: "Jasprit Bumrah",
        team_Name: "MI",
        price: "$4.3 Cr (INR)",
        isPlaying: true,
        status: "Playing",
        description: "Bowler",
      },
      {
        id: 5,
        playerName: "SanjayYadav",
        player_Name: "Sanjay Yadav",
        team_Name: "MI",
        price: "$34 Lakhs (INR)",
        isPlaying: true,
        status: "Playing",
        description: "Batsman",
      },
      {
        id: 6,
        playerName: "ArjunTendulkar",
        player_Name: "Arjun Tendulkar",
        team_Name: "MI",
        price: "$1.0 Cr (INR)",
        isPlaying: true,
        status: "Playing",
        description: "Batsman",
      },
      {
        id: 7,
        playerName: "TilakVerma",
        player_Name: "Tilak Verma",
        team_Name: "MI",
        price: "$1.2 Cr (INR)",
        isPlaying: true,
        status: "Playing",
        description: "Bowler",
      },
      {
        id: 8,
        playerName: "AryanJuyal",
        player_Name: "Aryan Juyal",
        team_Name: "MI",
        price: "$3 Cr (INR)",
        isPlaying: true,
        status: "Playing",
        description: "All-rounder",
      },
      {
        id: 9,
        playerName: "MuruganAshwin",
        player_Name: "Murugan Ashwin",
        team_Name: "MI",
        price: "$78 Lakhs (INR)",
        isPlaying: true,
        status: "Playing",
        description: "Bowler",
      },
      {
        id: 10,
        playerName: "RamandeepSingh",
        player_Name: "Ramandeep Singh",
        team_Name: "MI",
        price: "$3.7 Cr (INR)",
        isPlaying: true,
        status: "Playing",
        description: "Bolwer",
      },
      {
        id: 11,
        playerName: "TimDavid",
        player_Name: "Tim David",
        team_Name: "MI",
        price: "$45 Lakhs (INR)",
        status: "On-bench",
        isPlaying: false,
        description: "Bowler",
      },
    ],
  },
  {
    id: 4,
    name: "PNB",
    logo: "./Assets/Teams/pnb.jpg",
    "chamiponship count": 0,
    captain: "Shikhar Dhawan",
    "top batsman": "Shikhar Dhawan",
    "top bowler": "Rahul Chahara",
    color: "linear-gradient(160deg,red,rgb(231, 124, 124))",
    players: [
      {
        id: 0,
        playerName: "AnshPatel",
        player_Name: "Ansh Patel",
        team_Name: "PNB",
        price: "$5.1 Cr (INR)",
        isPlaying: true,
        status: "Playing",
        description: "Batsman",
      },
      {
        id: 1,
        playerName: "ShikharDhawan",
        player_Name: "Shikhar Dhawan",
        team_Name: "PNB",
        price: "$30 Lakhs (INR)",
        isPlaying: false,
        status: "On-bench",
        description: "Batsman",
      },
      {
        id: 11,
        playerName: "ArshdeepSingh",
        player_Name: "Arshdeep Singh",
        team_Name: "PNB",
        price: "$11.0 Cr (INR)",
        isPlaying: true,
        status: "Playing",
        description: "All-rounder",
      },
      {
        id: 2,
        playerName: "AtharvaTaide",
        player_Name: "Atharva Taide",
        team_Name: "PNB",
        price: "$8.0 Cr (INR)",
        isPlaying: true,
        status: "Playing",
        description: "All-rounder",
      },
      {
        id: 3,
        playerName: "BennyHowell",
        player_Name: "Benny Howell",
        team_Name: "PNB",
        price: "$5.3 Cr (INR)",
        isPlaying: true,
        status: "Playing",
        description: "Bowler",
      },
      {
        id: 4,
        playerName: "BhanukaRajapaksa",
        player_Name: "Bhanuka Rajapaksa",
        team_Name: "PNB",
        price: "$7.0 Cr (INR)",
        isPlaying: true,
        status: "Playing",
        description: "Batsman",
      },
      {
        id: 5,
        playerName: "JonnyBairstow",
        player_Name: "Jonny Bairstow",
        team_Name: "PNB",
        price: "$13.0 Cr (INR)",
        isPlaying: true,
        status: "Playing",
        description: "Batsman",
      },
      {
        id: 6,
        playerName: "MayankAgarwal",
        player_Name: "Mayank Agarwal",
        team_Name: "PNB",
        price: "$4.5 Cr (INR)",
        isPlaying: true,
        status: "Playing",
        description: "All-rounder",
      },
      {
        id: 7,
        playerName: "PrabhsimranSingh",
        player_Name: "Prabhsimran Singh",
        team_Name: "PNB",
        price: "$5.0 Cr (INR)",
        isPlaying: true,
        status: "Playing",
        description: "All-rounder",
      },
      {
        id: 8,
        playerName: "RahulChahar",
        player_Name: "Rahul Chahar",
        team_Name: "PNB",
        price: "$2.4 Cr (INR)",
        isPlaying: true,
        status: "Playing",
        description: "Bowler",
      },
      {
        id: 9,
        playerName: "SandeepSharma",
        player_Name: "Sandeep Sharma",
        team_Name: "PNB",
        price: "$5.1 Cr (INR)",
        isPlaying: true,
        status: "Playing",
        description: "Bowler",
      },
      {
        id: 10,
        playerName: "ShahrukhKhan",
        player_Name: "Shahrukh Khan",
        team_Name: "PNB",
        price: "$1.3 Cr (INR)",
        isPlaying: true,
        status: "Playing",
        description: "Bowler",
      },
    ],
  },
  {
    id: 5,
    name: "RR",
    logo: "./Assets/Teams/RR.jpg",
    "chamiponship count": 1,
    captain: "Sanju Samson",
    "top batsman": "Sanju Samson",
    "top bowler": "Jos Buttler",
    color: "linear-gradient(160deg,rgb(233, 66, 94),rgb(204, 134, 134))",
    players: [
      {
        id: 0,
        playerName: "CorbinBosch",
        player_Name: "Corbin Bosch",
        team_Name: "RR",
        price: "$23 Cr (INR)",
        isPlaying: true,
        status: "Playing",
        description: "Batsman",
      },
      {
        id: 1,
        playerName: "DarylMitchell",
        player_Name: "Daryl Mitchell",
        team_Name: "RR",
        price: "$10.0 Cr (INR)",
        isPlaying: true,
        status: "Playing",
        description: "All-rounder",
      },
      {
        id: 2,
        playerName: "JosButtler",
        player_Name: "Jos Buttler",
        team_Name: "RR",
        price: "$7.8 Cr (INR)",
        isPlaying: true,
        status: "Playing",
        description: "All-rounder",
      },
      {
        id: 3,
        playerName: "KarunNair",
        player_Name: "Karun Nair",
        team_Name: "RR",
        price: "$13.0 Cr (INR)",
        isPlaying: true,
        status: "Playing",
        description: "Batsman",
      },
      {
        id: 4,
        playerName: "KuldipYadav",
        player_Name: "Kuldip Yadav",
        team_Name: "RR",
        price: "$5.8 Cr (INR)",
        isPlaying: true,
        status: "Playing",
        description: "Batsman",
      },
      {
        id: 5,
        playerName: "RassieVanDerDussen",
        player_Name: "Der Dussen",
        team_Name: "RR",
        price: "$5.3 Cr (INR)",
        isPlaying: true,
        status: "Playing",
        description: "Bowler",
      },
      {
        id: 6,
        playerName: "RavichandranAshwin",
        player_Name: "R Ashwin",
        team_Name: "RR",
        price: "$4.7 Cr (INR)",
        isPlaying: true,
        status: "Playing",
        description: "All-rounder",
      },
      {
        id: 7,
        playerName: "SanjuSamson",
        player_Name: "Sanju Samson",
        team_Name: "RR",
        price: "$7.9 Cr (INR)",
        isPlaying: true,
        status: "Playing",
        description: "All-rounder",
      },
      {
        id: 8,
        playerName: "ShimronHetmyer",
        player_Name: "Shimron Hetmyer",
        team_Name: "RR",
        price: "$28 Lakhs (INR)",
        isPlaying: true,
        status: "Playing",
        description: "Bowler",
      },
      {
        id: 9,
        playerName: "ShubhamGarhwal",
        player_Name: "Shubham Garhwal",
        team_Name: "RR",
        price: "$96 Lakhs (INR)",
        isPlaying: true,
        status: "Playing",
        description: "Bowler",
      },
      {
        id: 10,
        playerName: "TrentBoult",
        player_Name: "Trent Boult",
        team_Name: "RR",
        price: "$1.3 Cr (INR)",
        isPlaying: true,
        status: "Playing",
        description: "Bowler",
      },
      {
        id: 11,
        playerName: "YuzvendraChahal",
        player_Name: "Yuzvendra Chahal",
        team_Name: "RR",
        price: "$30 Lakhs (INR)",
        isPlaying: true,
        status: "On-bench",
        description: "Bowler",
      },
    ],
  },
  {
    id: 6,
    name: "RCB",
    logo: "./Assets/Teams/RCB.jpg",
    "chamiponship count": 0,
    captain: "Virat Kohli",
    "top batsman": "Virat Kohli",
    "top bowler": "Yuzvendra Chahal",
    color: "linear-gradient(160deg,rgb(235, 220, 134),black)",
    players: [
      {
        id: 0,
        playerName: "DavidWilley",
        player_Name: "David Willey",
        team_Name: "RCB",
        price: "$4.0 Cr (INR)",
        isPlaying: true,
        status: "Playing",
        description: "Batsman",
      },
      {
        id: 1,
        playerName: "ViratKohli",
        player_Name: "Virat Kohli",
        team_Name: "RCB",
        price: "$10.0 Cr (INR)",
        isPlaying: true,
        status: "Playing",
        description: "All-rounder",
      },
      {
        id: 2,
        playerName: "DineshKarthik",
        player_Name: "Dinesh Karthik",
        team_Name: "RCB",
        price: "$8.5 Cr (INR)",
        isPlaying: true,
        status: "Playing",
        description: "All-rounder",
      },
      {
        id: 3,
        playerName: "FafduPlessis",
        player_Name: "Fafdu Plessis",
        team_Name: "RCB",
        price: "$13.3 Cr (INR)",
        isPlaying: true,
        status: "Playing",
        description: "Batsman",
      },
      {
        id: 4,
        playerName: "FinnAllen",
        player_Name: "Finn Allen",
        team_Name: "RCB",
        price: "$5.0 Cr (INR)",
        isPlaying: true,
        status: "Playing",
        description: "Batsman",
      },
      {
        id: 5,
        playerName: "GlennMaxwell",
        player_Name: "Glenn Maxwell",
        team_Name: "RCB",
        price: "$5.3 Cr (INR)",
        isPlaying: true,
        status: "Playing",
        description: "Bowler",
      },
      {
        id: 6,
        playerName: "HarshalPatel",
        player_Name: "Harshal Patel",
        team_Name: "RCB",
        price: "$4.9 Cr (INR)",
        isPlaying: true,
        status: "Playing",
        description: "All-rounder",
      },
      {
        id: 7,
        playerName: "JasonBehrendorff",
        player_Name: "Jason Behrendorff",
        team_Name: "RCB",
        price: "$7.0 Cr (INR)",
        isPlaying: true,
        status: "Playing",
        description: "All-rounder",
      },
      {
        id: 8,
        playerName: "MohammedSiraj",
        player_Name: "Mohammed Siraj",
        team_Name: "RCB",
        price: "$23 Lakhs (INR)",
        isPlaying: true,
        status: "Playing",
        description: "Bowler",
      },
      {
        id: 9,
        playerName: "RajatPatidar",
        player_Name: "Rajat Patidar",
        team_Name: "RCB",
        price: "$67 Lakhs (INR)",
        isPlaying: true,
        status: "Playing",
        description: "Bowler",
      },
      {
        id: 10,
        playerName: "ShahbazAhamad",
        player_Name: "Shahbaz Ahamad",
        team_Name: "RCB",
        price: "$1.3 Cr (INR)",
        isPlaying: true,
        status: "Playing",
        description: "Bowler",
      },
      {
        id: 11,
        playerName: "SiddharthKaul",
        player_Name: "Siddhar thKaul",
        team_Name: "RCB",
        price: "$38 Lakhs (INR)",
        isPlaying: true,
        status: "On-bench",
        description: "Bowler",
      },
    ],
  },
  {
    id: 7,
    name: "SRH",
    logo: "./Assets/Teams/srh.jpg",
    "chamiponship count": 1,
    captain: "Kane Williamson",
    "top batsman": "Kane Williamson",
    "top bowler": "Washington Sundar",
    color: "linear-gradient(160deg,rgb(228, 62, 62),rgb(255, 148, 9))",
    players: [
      {
        id: 0,
        playerName: "AbdulSamad",
        player_Name: "Abdul Samad",
        team_Name: "SRH",
        price: "$5.1 Cr (INR)",
        isPlaying: true,
        status: "Playing",
        description: "Batsman",
      },
      {
        id: 1,
        playerName: "AbhishekSharma",
        player_Name: "Abhishek Sharma",
        team_Name: "SRH",
        price: "$15.8 Cr (INR)",
        isPlaying: true,
        status: "Playing",
        description: "Batsman",
      },
      {
        id: 2,
        playerName: "AidenMarkram",
        player_Name: "Aiden Markram",
        team_Name: "SRH",
        price: "$5.9 Cr (INR)",
        isPlaying: true,
        status: "Playing",
        description: "Batsman",
      },
      {
        id: 3,
        playerName: "BhuvneshwarKumar",
        player_Name: "Bhuvneshwar Kumar",
        team_Name: "SRH",
        price: "$9.0Cr (INR)",
        isPlaying: true,
        status: "Playing",
        description: "All-rounder",
      },
      {
        id: 4,
        playerName: "KaneWilliamson",
        player_Name: "Kane Williamson",
        team_Name: "SRH",
        price: "$4.3 Cr (INR)",
        isPlaying: true,
        status: "Playing",
        description: "All-rounder",
      },
      {
        id: 5,
        playerName: "KartikTyagi",
        player_Name: "Kartik Tyagi",
        team_Name: "SRH",
        price: "$34 Lakhs (INR)",
        isPlaying: true,
        status: "Playing",
        description: "Batsman",
      },
      {
        id: 6,
        playerName: "MarcoJansen",
        player_Name: "Marco Jansenr",
        team_Name: "SRH",
        price: "$1.0 Cr (INR)",
        isPlaying: true,
        status: "Playing",
        description: "Batsman",
      },
      {
        id: 7,
        playerName: "RahulTripathi",
        player_Name: "Rahul Tripathi",
        team_Name: "SRH",
        price: "$1.2 Cr (INR)",
        isPlaying: true,
        status: "Playing",
        description: "Bowler",
      },
      {
        id: 8,
        playerName: "RavikumarSamarth",
        player_Name: "Ravikumar Samarth",
        team_Name: "SRH",
        price: "$3 Cr (INR)",
        isPlaying: true,
        status: "Playing",
        description: "All-rounder",
      },
      {
        id: 9,
        playerName: "ShreyasGopal",
        player_Name: "Shreyas Gopal",
        team_Name: "SRH",
        price: "$78 Lakhs (INR)",
        isPlaying: true,
        status: "Playing",
        description: "Bowler",
      },
      {
        id: 10,
        playerName: "UmranMalik",
        player_Name: "Umran Malik",
        team_Name: "SRH",
        price: "$3.7 Cr (INR)",
        isPlaying: true,
        status: "Playing",
        description: "Bolwer",
      },
      {
        id: 11,
        playerName: "WashingtonSundar",
        player_Name: "Washington Sundar",
        team_Name: "SRH",
        price: "$45 Lakhs (INR)",
        status: "On-bench",
        isPlaying: false,
        description: "Bowler",
      },
    ],
  },
];

let image = document.getElementById("image");
let pic = document.createElement("img");
pic.setAttribute(
  "src",
  `./Assets/Teams/${teamsData[id]["name"]}/${teamsData[id]["players"][playerId]["playerName"]}.jpeg`
);
pic.setAttribute("width", "100%");
pic.setAttribute("height", "100%");
image.appendChild(pic);

let pname = document.getElementById("pname");
let tname = document.getElementById("tname");
let price = document.getElementById("price");
let status = document.getElementById("status");
let role = document.getElementById("role");

pname.innerText = teamsData[id]["players"][playerId]["player_Name"];
price.innerText = teamsData[id]["players"][playerId]["price"];
tname.innerText = teamsData[id]["players"][playerId]["team_Name"];
status.innerText = teamsData[id]["players"][playerId]["status"];
role.innerText = teamsData[id]["players"][playerId]["description"];
